linters:
  enable:
    - revive
    - goimports
    - staticcheck
    - unconvert
    - bodyclose
    - goconst
    - godot
    - gofmt
    - misspell
    - prealloc
    - revive
    - stylecheck
    - unused
    - whitespace
    - unparam
    - errcheck

linter-settings:
  errcheck: 
    check-type-assertions: true
    check-blank: true
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0