name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.6'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Start Test Database
        run: docker compose -f docker-compose.test.yml --project-name merch_test up -d

      - name: Wait for DB to be ready
        run: sleep 10

      - name: Run Tests
        run: go test -v ./... -p 1

      - name: Stop Test Database
        if: always()
        run: docker compose -f docker-compose.test.yml --project-name merch_test down
